### ISSUE TITLE
[Issue] Could not pass event InventoryClickEvent to Essentials_WarpGUI v2.2.1

### ISSUE THREAD

**Issue by Kaisiq** [MrEAlderson/EssentialsWarpGUI#6]
**Error**

[21:38:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Essentials_WarpGUI v2.2.1
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_272]
at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_272]
at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_272]
at de.marcely.ezgui.BaseGUI.close(BaseGUI.java:50) ~[?:?]
at de.marcely.ezgui.BaseGUI.close(BaseGUI.java:41) ~[?:?]
at de.marcely.warpgui.command.WarpCommand$1.onClick(WarpCommand.java:135) ~[?:?]
at de.marcely.ezgui.EventsManager.onInventoryClickEvent(EventsManager.java:40) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-204]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-204]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-204]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-204]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]

**What do you think caused the issue**
That error hasn't appeared until today, I updated Java from version 8 to 11 around a week ago, I think it could be that.

**Comment by MrEAlderson** [comment]
Fixed with https://github.com/MrEAlderson/EssentialsWarpGUI/commit/a63225d95a702bbe44125f1424517bb3597d3aa4
